version: '3.8'

services:
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: mysql-db
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: